-- Up Migration

ALTER TABLE recipes ADD COLUMN user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE;
CREATE INDEX idx_recipes_user_id ON recipes(user_id);

ALTER TABLE tags ADD COLUMN user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE;
CREATE INDEX idx_tags_user_id ON tags(user_id);

ALTER TABLE categories ADD COLUMN user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE;
CREATE INDEX idx_categories_user_id ON categories(user_id);

ALTER TABLE ai_settings DROP CONSTRAINT IF EXISTS ai_settings_id_check;
ALTER TABLE ai_settings ALTER COLUMN id DROP DEFAULT;
ALTER TABLE ai_settings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE ai_settings ADD COLUMN user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE ai_settings ADD CONSTRAINT ai_settings_user_id_key UNIQUE (user_id);

-- Down Migration

ALTER TABLE ai_settings DROP CONSTRAINT IF EXISTS ai_settings_user_id_key;
ALTER TABLE ai_settings DROP COLUMN IF EXISTS user_id;
ALTER TABLE ai_settings ALTER COLUMN id DROP IDENTITY IF EXISTS;
ALTER TABLE ai_settings ALTER COLUMN id SET DEFAULT 1;
ALTER TABLE ai_settings ADD CONSTRAINT ai_settings_id_check CHECK (id = 1);

DROP INDEX IF EXISTS idx_categories_user_id;
ALTER TABLE categories DROP COLUMN IF EXISTS user_id;

DROP INDEX IF EXISTS idx_tags_user_id;
ALTER TABLE tags DROP COLUMN IF EXISTS user_id;

DROP INDEX IF EXISTS idx_recipes_user_id;
ALTER TABLE recipes DROP COLUMN IF EXISTS user_id;
