import { ORIGIN, BETTER_AUTH_SECRET, COOKIE_SECURE, DISABLE_RATE_LIMITS } from '$app/env/private';
import { dev } from '$app/env';
import { betterAuth } from 'better-auth/minimal';
import { drizzleAdapter } from 'better-auth/adapters/drizzle';
import { sveltekitCookies } from 'better-auth/svelte-kit';
import { getRequestEvent } from '$app/server';
import { db } from '#lib/server/db/index.ts';
import { accounts, sessions, users, verifications } from '#lib/server/db/schema.ts';
import { cleanUpFamilyAfterDelete } from '#lib/server/services/account-deletion.ts';
import { isEmailConfigured, sendPasswordResetEmail } from '#lib/server/services/email.ts';
import { createFamily } from '#lib/server/services/family.ts';
import { CLIENT_ADDRESS_HEADER } from '#lib/server/client-address.ts';

const THIRTY_DAYS_SECONDS = 60 * 60 * 24 * 30;
const ONE_HOUR_SECONDS = 60 * 60;

export const auth = betterAuth({
	appName: 'Yumbry',
	baseURL: ORIGIN,
	// The default, spelled out: the e2e suite signs up through /api/auth/sign-up/email.
	basePath: '/api/auth',
	// Must stay the secret the Express app used, or every existing session is invalidated.
	secret: BETTER_AUTH_SECRET,
	// The tables are the ones the Prisma app created (plural, snake_case columns), so they are
	// passed explicitly rather than generated by `@better-auth/cli`.
	database: drizzleAdapter(db, {
		provider: 'pg',
		schema: { user: users, session: sessions, account: accounts, verification: verifications }
	}),

	emailAndPassword: {
		enabled: true,
		autoSignIn: true,
		minPasswordLength: 8,
		maxPasswordLength: 72,
		resetPasswordTokenExpiresIn: ONE_HOUR_SECONDS,
		// Resetting a password drops the user's session rows outright.
		revokeSessionsOnPasswordReset: true,
		sendResetPassword: async ({ user, token }) => {
			// Without email configured this does nothing, so /forgot-password still shows its generic
			// confirmation rather than an error. better-auth's own `url` is ignored: the email links to
			// /reset-password?token=…, as main's did.
			if (!isEmailConfigured()) return;
			await sendPasswordResetEmail(user.email, token);
		}
	},

	user: {
		additionalFields: {
			// input: false on all of these keeps them off both the signup payload and better-auth's
			// own updateUser endpoint; preferences are written by the app, validated against the
			// shared enums.
			//
			// required: false is not optional here despite the column being NOT NULL: better-auth
			// validates required fields against the request payload before databaseHooks runs, so a
			// required familyId the client may not send could never be satisfied. The create hook
			// always supplies one, and the NOT NULL constraint is what actually guarantees it.
			familyId: { type: 'number', required: false, input: false },
			locale: { type: 'string', required: true, defaultValue: 'en', input: false },
			unitSystem: { type: 'string', required: true, defaultValue: 'metric', input: false },
			smallVolumes: { type: 'string', required: true, defaultValue: 'spoons', input: false },
			jsonImportExportEnabled: {
				type: 'boolean',
				required: true,
				defaultValue: false,
				input: false
			}
		},
		changeEmail: { enabled: false },
		// The settings page calls this with the user's password, which skips the session freshness
		// check. The family clean-up runs once the user row is gone.
		deleteUser: { enabled: true, afterDelete: cleanUpFamilyAfterDelete }
	},

	session: {
		expiresIn: THIRTY_DAYS_SECONDS,
		updateAge: 60 * 60 * 24
		// cookieCache is deliberately left off. It would let getSession answer from the cookie
		// without touching the database, serving a stale familyId for the cache lifetime — so a
		// user who just left a family would keep reading its recipes.
	},

	advanced: {
		// Unchanged from the Express app, so existing session cookies keep working.
		cookiePrefix: 'yumbry',
		useSecureCookies: COOKIE_SECURE,
		defaultCookieAttributes: { sameSite: 'lax', httpOnly: true },
		// hooks.server.ts puts adapter-node's client address here on every request. Without it the
		// rate limiter sees no IP behind the tunnel and falls back to one shared bucket per path.
		ipAddress: { ipAddressHeaders: [CLIENT_ADDRESS_HEADER] }
	},

	rateLimit: {
		// Off in dev; DISABLE_RATE_LIMITS=1 turns it off for the E2E suite's production build.
		enabled: !dev && !DISABLE_RATE_LIMITS,
		window: 60,
		max: 100,
		customRules: {
			'/sign-in/email': { window: 900, max: 10 },
			'/sign-up/email': { window: 900, max: 10 },
			'/request-password-reset': { window: 900, max: 5 },
			'/reset-password': { window: 900, max: 10 },
			'/change-password': { window: 900, max: 10 },
			'/delete-user': { window: 900, max: 10 }
		}
	},

	databaseHooks: {
		user: {
			create: {
				before: async (user) => {
					// Every user starts in a personal family of one, so users.family_id is never null.
					// The family is written before the user insert, so a failing insert (duplicate
					// email) leaves an empty family row behind — harmless, and swept later.
					const family = await createFamily();
					return { data: { ...user, familyId: family.id } };
				}
			}
		}
	},

	plugins: [
		sveltekitCookies(getRequestEvent) // make sure this is the last plugin in the array
	]
});

export type Session = typeof auth.$Infer.Session;
